### PR TITLE
Add Gradle repositories for buildscript dependencies

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

When trying to build the app with Gradle, I get the following error:
```
A problem occurred configuring root project 'monkeyboard-radio-android'.
> Could not resolve all files for configuration ':classpath'.
   > Cannot resolve external dependency com.android.tools.build:gradle:3.0.1 because no repositories are defined.
     Required by:
         project :
```

This pull request fixes it.

### CODE REVIEW

**Comment by freshollie** [comment]
Thanks for the info and fix 👍

**Comment by IzzySoft** [comment]
Thanks for merging, @freshollie! Is there a chance for a new tag that points to a commit including this fix, so F-Droid can build the app (see [here](https://gitlab.com/fdroid/rfp/issues/600))?

**Comment by freshollie** [comment]
Done, hopefully this is fixed.

**Comment by IzzySoft** [comment]
Thanks! Completed the RFP and marked it ready-to-build. If you wish, you could provide screenshots via Fastlane/Triple-T, see [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/).

**Pull request merged**
